export const A = {
  bg:          "var(--admin-bg)",
  bgSoft:      "var(--admin-bg-soft)",
  sidebar:     "var(--admin-sidebar)",
  card:        "var(--admin-card)",
  cardWarm:    "var(--admin-card-warm)",
  border:      "var(--admin-border)",
  borderSoft:  "var(--admin-border-soft)",
  divider:     "var(--admin-divider)",
  ink:         "var(--admin-ink)",
  inkMid:      "var(--admin-ink-mid)",
  inkSoft:     "var(--admin-ink-soft)",
  inkFaint:    "var(--admin-ink-faint)",
  clay:        "var(--admin-clay)",
  clayDark:    "var(--admin-clay-dark)",
  clayLight:   "var(--admin-clay-light)",
  claySoft:    "var(--admin-clay-soft)",
  amber:       "var(--admin-amber)",
  amberLight:  "var(--admin-amber-light)",
  green:       "var(--admin-green)",
  greenLight:  "var(--admin-green-light)",
  red:         "var(--admin-red)",
  redLight:    "var(--admin-red-light)",
  plum:        "var(--admin-plum)",
  plumLight:   "var(--admin-plum-light)",
  shadow:      "var(--admin-shadow)",
} as const;
