export const N = {
  green:       "var(--nanny-green)",
  greenDk:     "var(--nanny-green-dk)",
  greenLt:     "var(--nanny-green-lt)",
  greenMid:    "var(--nanny-green-mid)",
  bgDeep:      "var(--nanny-bg-deep)",
  bg:          "var(--bg)",
  card:        "var(--nanny-card)",
  cardSoft:    "var(--nanny-card-soft)",
  border:      "var(--nanny-border)",
  borderSoft:  "var(--nanny-border-soft)",
  inkSoft:     "var(--nanny-ink-soft)",
  inkMute:     "var(--nanny-ink-mute)",
  inkFaint:    "var(--nanny-ink-faint)",
  gold:        "var(--nanny-gold)",
  goldLt:      "var(--nanny-gold-lt)",
  rose:        "var(--nanny-rose)",
  roseLt:      "var(--nanny-rose-lt)",
  amber:       "var(--nanny-amber)",
  amberLt:     "var(--nanny-amber-lt)",
  shadow:      "var(--nanny-shadow)",
  shadowMd:    "var(--nanny-shadow-md)",
} as const;
